export const UPDATE_SCORE = 'UPDATE_SCORE';
export const SET_OPTIONS_LIST = 'SET_OPTIONS_LIST';
export const SHOW_DESCRIPTION = 'SHOW_DESCRIPTION';
export const SWITCH_CATEGORY = 'SWITCH_CATEGORY';
export const SET_CATEGORY = 'SET_CATEGORY';
export const SET_DATA = 'SET_DATA';
