const SCORE = 'SCORE';
const STATUS = 'STATUS';
const ELEMENTS_LIST = 'ELEMENTS_LIST';
const CATEGORIES = 'CATEGORIES';
const DATA = 'DATA';
const CURRENT_DESCRIPTION = 'CURRENT_DESCRIPTION';

export {
  SCORE,
  STATUS,
  ELEMENTS_LIST,
  CATEGORIES,
  DATA,
  CURRENT_DESCRIPTION,
};
